ඞ params ඞ descs ඞ
alloc8or/gta5-nativedb-data pull request #198
Opened 2022-10-10 20:23 UTC by yasmasdas

ඞ params ඞ descs ඞ

2022-10-24 19:14 UTC, alloc8or requested changes

2022-10-24 19:14 UTC, alloc8or commented on natives.json
> -			"comment": "This native does absolutely nothing, just a nullsub",
Last time I checked this was still a nullsub. Did you remove this by mistake?

2022-10-24 19:14 UTC, alloc8or commented on natives.json
> -			"comment": "This native does absolutely nothing, just a nullsub",
Last time I checked this was still a nullsub. Did you remove this by mistake?

2022-10-24 19:14 UTC, alloc8or commented on natives.json
> -			"comment": "Doesn't actually return anything.",
This should ideally not be removed. Some natives (such as this one) are defined to have a non-`void` return type for script, but are actually `void` in code.
Since we strictly follow the script definition for return types, this might yield unexpected results (e.g. 0/false all the time), so this comment is a warning that you shouldn't use the return value.

2022-10-24 19:14 UTC, alloc8or commented on natives.json
> +			"comment": "Sets an value related to timecycles.",
Forgot to change 'an' -> 'a' here.

2022-10-29 11:23 UTC, yasmasdas commented on natives.json
> -			"comment": "This native does absolutely nothing, just a nullsub",
I really thought I checked PLAYSTATS_ODDJOB_DONE and SET_MULTIPLAYER_HUD_CASH but after some examination they indeed seem like nullsubs

Regarding the return type thing, i also did not know that sorry I didn't look at it in a ida either I just saw the return type being bool

2022-11-11 13:18 UTC, merged