Update / Add links to full lists of related data
alloc8or/gta5-nativedb-data pull request #32
Opened 2020-12-23 13:17 UTC by DurtyFree

This updates and adds several links to full lists of related data, links point to this GitHub repo: https://github.com/DurtyFree/gta-v-data-dumps which is maintained and updated by me for each GTA V update

2020-12-23 20:29 UTC, alloc8or requested changes

2020-12-23 20:29 UTC, alloc8or commented on natives.json
> +			"jhash": "Full list of static emitters by DurtyFree: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/staticEmitters.json",
Wrong field.

2020-12-23 20:29 UTC, alloc8or commented on natives.json
> +			"jhash": "Full list of animpostFX / screen effects by DurtyFree: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/animPostFxNamesCompact.json",
Wrong field.

2020-12-24 12:45 UTC, DurtyFree commented on natives.json
> +			"jhash": "Full list of animpostFX / screen effects by DurtyFree: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/animPostFxNamesCompact.json",
Fixed thanks

2020-12-24 12:45 UTC, DurtyFree commented on natives.json
> +			"jhash": "Full list of static emitters by DurtyFree: https://github.com/DurtyFree/gta-v-data-dumps/blob/master/staticEmitters.json",
Fixed thanks

2020-12-24 12:45 UTC, DurtyFree commented
I have fixed the comments at the wrong fields

2020-12-24 23:29 UTC, merged